const canvas=document.getElementById('gameCanvas');const engine=new HermesEngine(canvas);const tree=document.getElementById('sceneTree');const inspector=document.getElementById('inspector');const selectedType=document.getElementById('selectedType');const consoleLog=document.getElementById('consoleLog');
function log(msg,type='ok'){const row=document.createElement('div');row.className=`log-${type}`;row.textContent=`[${new Date().toLocaleTimeString()}] ${msg}`;consoleLog.prepend(row)}
const ai=new HermesCopilot(engine,m=>log(`Hermes: ${m}`,'ai'));
function esc(v){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function renderTree(){tree.innerHTML='';engine.world.entities.forEach(e=>{const div=document.createElement('div');div.className='tree-item'+(e.id===engine.selectedId?' active':'');div.innerHTML=`<span class="tree-dot" style="--entity-color:${e.color}"></span><span>${esc(e.name)}</span>`;div.onclick=()=>engine.select(e.id);tree.appendChild(div)})}
function renderInspector(){const e=engine.selected();if(!e){inspector.className='inspector empty-state';inspector.textContent='Selecciona una entidad';selectedType.textContent='—';return}inspector.className='inspector';selectedType.textContent=e.type.toUpperCase();inspector.innerHTML=`<div class="field"><label>Nombre</label><input data-k="name" value="${esc(e.name)}"></div><div class="field-row"><div class="field"><label>X</label><input data-k="x" type="number" value="${Math.round(e.x)}"></div><div class="field"><label>Y</label><input data-k="y" type="number" value="${Math.round(e.y)}"></div></div><div class="field"><label>Color</label><input data-k="color" type="color" value="${e.color}"></div>${e.speed?`<div class="field"><label>Velocidad</label><input data-k="speed" type="number" value="${e.speed}"></div>`:''}${e.hp?`<div class="field"><label>Vida</label><input data-k="hp" type="number" value="${e.hp}"></div>`:''}<button id="deleteBtn" class="danger-btn">Eliminar entidad</button>`;inspector.querySelectorAll('input').forEach(i=>i.addEventListener('input',()=>{const k=i.dataset.k;e[k]=i.type==='number'?Number(i.value):i.value;renderTree();engine.emit('change')}));document.getElementById('deleteBtn').onclick=()=>{engine.remove(e.id);renderAll();log(`Entidad eliminada: ${e.name}`,'warn')}}
function renderAll(){renderTree();renderInspector()}
engine.on('select',renderAll);engine.on('change',()=>{renderTree();renderInspector()});
function add(type){const e=engine.add(type);renderAll();log(`Entidad creada: ${e.name}`)}document.querySelectorAll('[data-create]').forEach(b=>b.onclick=()=>add(b.dataset.create));document.getElementById('addEntityBtn').onclick=()=>add('obstacle');
const playBtn=document.getElementById('playBtn');playBtn.onclick=()=>{engine.playing=!engine.playing;playBtn.textContent=engine.playing?'■ Detener':'▶ Jugar';document.getElementById('modeLabel').textContent=engine.playing?'PLAY MODE':'EDIT MODE';log(engine.playing?'Ejecutando juego. Usa WASD o flechas.':'Juego detenido.','ok')};
document.getElementById('saveBtn').onclick=()=>{localStorage.setItem('hermes-game-project',engine.serialize());log('Proyecto guardado localmente.')};document.getElementById('newBtn').onclick=()=>{engine.seedWorld();engine.world.night=false;engine.selectedId=null;renderAll();log('Escena reiniciada.','warn')};document.getElementById('exportBtn').onclick=()=>{const blob=new Blob([engine.serialize()],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='hermes-game-project.json';a.click();URL.revokeObjectURL(a.href);log('Proyecto exportado como JSON.')};
const chat=document.getElementById('chatHistory');function message(text,who='ai'){const d=document.createElement('div');d.className=`msg ${who}`;d.innerHTML=`<span>${who==='user'?'Y':'H'}</span><p>${esc(text)}</p>`;chat.appendChild(d);chat.scrollTop=chat.scrollHeight}
function executePrompt(text){if(!text.trim())return;message(text,'user');log(`Prompt: ${text}`,'ai');setTimeout(()=>{const answer=ai.run(text);message(answer,'ai');renderAll()},180)}document.getElementById('promptForm').addEventListener('submit',e=>{e.preventDefault();const input=document.getElementById('promptInput');const t=input.value;input.value='';executePrompt(t)});document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>executePrompt(b.dataset.prompt));
try{const saved=localStorage.getItem('hermes-game-project');if(saved)engine.load(JSON.parse(saved))}catch{}renderAll();log('Hermes Game Engine V0.1 listo.','ok');log('Runtime Canvas inicializado · IA local de herramientas activa.','ai');
