class HermesEngine {
  constructor(canvas) {
    this.canvas = canvas; this.ctx = canvas.getContext('2d'); this.playing = false;
    this.selectedId = null; this.keys = new Set(); this.last = performance.now(); this.listeners = [];
    this.world = { theme:'cyber', night:false, entities:[], camera:{x:0,y:0} };
    this.seedWorld(); this.bindInput(); this.resize(); window.addEventListener('resize',()=>this.resize()); requestAnimationFrame(t=>this.loop(t));
  }
  seedWorld(){ this.world.entities=[
    this.entity('player','Player',640,420,'#46e6ff',{speed:220,hp:100,size:24}),
    this.entity('npc','Fixer NPC',415,345,'#b372ff',{hp:100,size:20}),
    this.entity('enemy','Drone 01',890,330,'#ff5d7a',{speed:70,hp:45,size:22}),
    this.entity('coin','Data Shard',750,515,'#ffd166',{size:12}),
    this.entity('obstacle','Neon Kiosk',300,485,'#3a4558',{w:90,h:46,size:24}) ]; }
  entity(type,name,x,y,color,props={}){ return {id:crypto.randomUUID(),type,name,x,y,color,...props}; }
  add(type,props={}){ const defaults={enemy:['Enemy','#ff5d7a'],coin:['Coin','#ffd166'],npc:['NPC','#b372ff'],obstacle:['Object','#566176']}; const d=defaults[type]||['Entity','#46e6ff']; const e=this.entity(type,props.name||d[0],props.x??(220+Math.random()*800),props.y??(160+Math.random()*390),props.color||d[1],props); this.world.entities.push(e); this.select(e.id); this.emit('change',e); return e; }
  remove(id){ this.world.entities=this.world.entities.filter(e=>e.id!==id); if(this.selectedId===id)this.selectedId=null; this.emit('change'); }
  select(id){this.selectedId=id;this.emit('select',this.selected());}
  selected(){return this.world.entities.find(e=>e.id===this.selectedId)||null}
  on(type,fn){this.listeners.push({type,fn})} emit(type,data){this.listeners.filter(l=>l.type===type).forEach(l=>l.fn(data))}
  bindInput(){ window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','w','a','s','d','W','A','S','D'].includes(e.key) && document.activeElement?.tagName!=='TEXTAREA')e.preventDefault();this.keys.add(e.key.toLowerCase())}); window.addEventListener('keyup',e=>this.keys.delete(e.key.toLowerCase())); this.canvas.addEventListener('pointerdown',e=>{if(this.playing)return;const r=this.canvas.getBoundingClientRect();const x=(e.clientX-r.left)*this.canvas.width/r.width,y=(e.clientY-r.top)*this.canvas.height/r.height;const hit=[...this.world.entities].reverse().find(o=>Math.hypot(o.x-x,o.y-y)<Math.max(18,o.size||18));if(hit)this.select(hit.id)}) }
  update(dt){ if(!this.playing)return; const p=this.world.entities.find(e=>e.type==='player'); if(!p)return; let dx=0,dy=0;if(this.keys.has('a')||this.keys.has('arrowleft'))dx--;if(this.keys.has('d')||this.keys.has('arrowright'))dx++;if(this.keys.has('w')||this.keys.has('arrowup'))dy--;if(this.keys.has('s')||this.keys.has('arrowdown'))dy++;if(dx||dy){const len=Math.hypot(dx,dy);const boost=this.keys.has(' ')?1.75:1;p.x=Math.max(24,Math.min(this.canvas.width-24,p.x+dx/len*p.speed*boost*dt));p.y=Math.max(90,Math.min(this.canvas.height-24,p.y+dy/len*p.speed*boost*dt))} this.world.entities.filter(e=>e.type==='enemy').forEach((e,i)=>{e.x+=Math.sin(performance.now()/900+i)*e.speed*dt*.23;e.y+=Math.cos(performance.now()/1100+i)*e.speed*dt*.12}) }
  resize(){const r=this.canvas.parentElement.getBoundingClientRect();const ratio=16/9;let w=r.width,h=r.height;if(w/h>ratio)w=h*ratio;else h=w/ratio;this.canvas.style.width=`${w}px`;this.canvas.style.height=`${h}px`}
  drawGrid(){const c=this.ctx,w=this.canvas.width,h=this.canvas.height; const bg=this.world.night?'#05070d':'#0a1119'; c.fillStyle=bg;c.fillRect(0,0,w,h); c.strokeStyle=this.world.night?'#111727':'#162333';c.lineWidth=1;for(let x=0;x<w;x+=40){c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke()}for(let y=0;y<h;y+=40){c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke()} c.fillStyle='#0f1822';c.fillRect(0,520,w,200);c.fillStyle='#152231';c.fillRect(0,555,w,88);c.setLineDash([26,24]);c.strokeStyle='#d9c77366';c.lineWidth=3;c.beginPath();c.moveTo(0,599);c.lineTo(w,599);c.stroke();c.setLineDash([]); ['#16d8f055','#c64cff44','#16d8f033'].forEach((color,i)=>{c.fillStyle=color;c.fillRect(70+i*370,140+i*55,220,5)}); }
  drawEntity(e){const c=this.ctx,sel=e.id===this.selectedId&&!this.playing;c.save();c.translate(e.x,e.y);c.shadowBlur=18;c.shadowColor=e.color;c.fillStyle=e.color;if(e.type==='coin'){c.rotate(performance.now()/800);c.fillRect(-8,-8,16,16)}else if(e.type==='enemy'){c.beginPath();c.moveTo(0,-18);c.lineTo(19,15);c.lineTo(-19,15);c.closePath();c.fill();c.fillStyle='#111';c.fillRect(-6,-4,12,6)}else if(e.type==='npc'){c.beginPath();c.arc(0,0,17,0,Math.PI*2);c.fill();c.fillStyle='#0c0d13';c.fillRect(-7,-3,14,5)}else if(e.type==='obstacle'){c.fillRect(-(e.w||70)/2,-(e.h||42)/2,e.w||70,e.h||42);c.fillStyle='#46e6ff88';c.fillRect(-(e.w||70)/2+8,-(e.h||42)/2+7,(e.w||70)-16,3)}else{c.beginPath();c.arc(0,0,18,0,Math.PI*2);c.fill();c.fillStyle='#071119';c.beginPath();c.arc(0,-3,7,0,Math.PI*2);c.fill();c.fillRect(-6,4,12,14)}c.shadowBlur=0;if(sel){c.strokeStyle='#fff';c.lineWidth=1;c.setLineDash([4,4]);c.strokeRect(-30,-30,60,60);c.setLineDash([])}c.font='11px system-ui';c.textAlign='center';c.fillStyle='#dfe9f8';c.fillText(e.name,0,(e.type==='obstacle'?(e.h||42)/2:20)+18);c.restore()}
  render(){this.drawGrid();this.world.entities.forEach(e=>this.drawEntity(e));const c=this.ctx;c.fillStyle='#0009';c.fillRect(18,18,220,48);c.fillStyle='#46e6ff';c.font='bold 13px system-ui';c.fillText(this.playing?'PLAY MODE':'EDIT MODE',32,39);c.fillStyle='#7f8ca3';c.font='10px system-ui';c.fillText(`${this.world.entities.length} entities · ${this.world.night?'night':'day'}`,32,56)}
  loop(t){const dt=Math.min(.05,(t-this.last)/1000);this.last=t;this.update(dt);this.render();requestAnimationFrame(n=>this.loop(n))}
  serialize(){return JSON.stringify({version:'0.1',project:'Cyber Medellín',world:this.world},null,2)}
  load(data){if(data?.world){this.world=data.world;this.selectedId=null;this.emit('change')}}
}
